# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

[package]
name = "kicad-text-injector"
version = "0.2.1"
authors = ["Robin Vobruba <hoijui.quaero@gmail.com>"]
description = """
    A tiny CLI tool that replaces variables of the style `${KEY}`
    within KiCad PCB (pcbnew) files.
    """
license = "GPL-3.0-or-later"
repository = "https://github.com/hoijui/kicad-text-injector"
keywords = ["cli", "ci", "kicad"]
categories = ["command-line-utilities", "text-processing"]
edition = "2018"

[dependencies]
clap = "3.0.0-beta.2"
regex = "1"
dict = "0.1.5"
repvar = { version = "0.1.17", path = "../repvar" }
