#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Vobruba <hoijui.quaero@gmail.com>
#
# SPDX-License-Identifier: Unlicense

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
set -Eeuo pipefail
#set -Eeu

#script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
#source "$script_dir/env"

if [ "$1" = "--all" ]
then
  # delere *everything*!
  # everything?
  # eeeeeverything (generated)!
  rm -Rf target/*
else
  # By default, do not remove the stuff that takes long to compile,
  # but is largely not project specific
  find ./target | grep -v "/build" | grep -v "/deps"
fi
